import type { CanonicalVisualRuntimePort, DeterministicPort, EvidenceSink, CameraState } from '../contracts';
import { emitStageEvidence } from '../evidence';
import { sampleShot } from './cameraPathPlanner';
import { detectTemporalDiscontinuity } from './temporalDiscontinuityGuard';
import { clampCameraOptics } from './focusExposure';
import { buildCaptureManifest } from './captureManifest';
import type { CaptureFrameRecord, CaptureManifest, CinematicShot } from './cinematicTypes';
export function captureCinematicSequence(args:{readonly captureId:string;readonly shots:readonly CinematicShot[];readonly deterministic:DeterministicPort;readonly evidence:EvidenceSink;readonly visual:CanonicalVisualRuntimePort;readonly width:number;readonly height:number}):CaptureManifest{const records:CaptureFrameRecord[]=[]; let previous:CameraState|undefined; let globalFrame=0; let fps=30; for(const shot of args.shots){fps=shot.fps; for(const sampled of sampleShot(shot)){const clamped=clampCameraOptics(sampled.camera,{minFocusDistance:0.02,maxFocusDistance:500,minFStop:0.8,maxFStop:22,minExposureEv:-8,maxExposureEv:8}); const decision=detectTemporalDiscontinuity(previous,clamped,sampled.temporalHistoryReset); args.visual.applyCamera(clamped,decision.resetHistory); const probe=args.visual.captureFrame(globalFrame); records.push({shotId:shot.shotId,frameIndex:globalFrame,timeS:sampled.timeS,cameraFingerprint:args.deterministic.fingerprint(clamped),renderFingerprint:probe.frameFingerprint,temporalHistoryReset:decision.resetHistory}); previous=clamped; globalFrame+=1;}}
 const manifest=buildCaptureManifest({captureId:args.captureId,fps,width:args.width,height:args.height,frames:records,deterministic:args.deterministic}); emitStageEvidence({sink:args.evidence,deterministic:args.deterministic,type:'CINEMATIC_CAPTURE_COMPLETED',stage:'V6.1',modelId:'cinematic-capture-v6.1',input:args.shots,result:manifest,epistemicStatus:'SIMULATION',evidenceClass:'DERIVED',provenance:[{sourceId:'canonical-visual-runtime',sourceType:'SYSTEM'}]}); return manifest;}
