/**
 * DOME WORLD — real, cited reference figures the model is judged against.
 *
 * Every value here is an independently-documented historical measurement or
 * standard geodesic derivation — never generated by `domeModel.ts`, never
 * adjusted to make either outcome come out a particular way. Adapted from
 * external drafts (Qwen); kept only citations that need no invented mapping
 * to compare against the model (see `domeModel.ts`'s module doc for why the
 * first draft's star-altitude citation was dropped for exactly that reason).
 *
 * `SUNRISE_TIME_DIFFERENCE_MINUTES` and `EARTH_MOON_SHADOW_RATIO` below are
 * real, correctly-sourced figures from a second Qwen draft, but they are
 * deliberately NOT wired into `domeChallenge.ts` as test cases, for the same
 * "no invented mapping" reason: `domeModel.ts` only models a static gnomon
 * shadow and a flat-plane visibility horizon from its two declared
 * parameters (`sunHeightKm`, `atmosphericVisibilityKm`) — it has no sun-path
 * or Earth-cross-section model to derive a predicted sunrise-time offset or
 * shadow-ratio from. Producing a "flat-model prediction" for either would
 * mean inventing sun-motion or planet-shape assumptions found nowhere in
 * the existing model, not reading one off it. They are kept here as
 * reference data for a future, genuinely principled model extension.
 */

export interface DomeReferenceCitation {
  readonly citationText: string;
  readonly sourceRef: string;
  readonly measuredValue: number;
  readonly unit: string;
  /** Half-width the citation itself is willing to stand behind — never invented for this comparison. */
  readonly uncertainty: number;
}

/**
 * Eratosthenes' shadow measurement (~240 BC): at summer solstice noon, the
 * sun was directly overhead at Syene (0° shadow) while a gnomon at
 * Alexandria, ~800 km away, cast a 7.2° shadow (1/50th of a circle).
 */
export const ERATOSTHENES_SHADOW_ANGLE: DomeReferenceCitation = {
  citationText: 'At Alexandria, ~800 km from Syene (where the sun was directly overhead), a gnomon cast a shadow of 7.2 degrees (1/50th of a circle) at summer solstice noon.',
  sourceRef: 'Eratosthenes via Cleomedes, De Motu Circulari Corporum Caelestium, Book 1 (~240 BC)',
  measuredValue: 7.2,
  unit: 'degrees',
  uncertainty: 0.5,
};

export const ERATOSTHENES_GROUND_DISTANCE_KM = 800;

/**
 * Standard geodesy: distance to the geometric horizon for an observer at
 * height h above a sphere of radius R is d = sqrt(2Rh + h^2). For h = 1.7 m
 * (average eye level) and R = 6371 km, d ~= 4.65 km — independently
 * confirmed by maritime observation (ships going hull-down at this range).
 */
export const HORIZON_DISTANCE_1_7M: DomeReferenceCitation = {
  citationText: 'Distance to the geometric horizon for an observer at 1.7 m height on a sphere of radius 6371 km, via d = sqrt(2Rh + h^2); confirmed by maritime hull-down observation.',
  sourceRef: 'Standard geodesy formula d = sqrt(2Rh + h^2), R = 6371 km, h = 1.7 m',
  measuredValue: 4.65,
  unit: 'km',
  uncertainty: 0.2,
};

export const HORIZON_OBSERVER_HEIGHT_M = 1.7;

/**
 * On 2024-03-20 (spring equinox), sunrise in Denver, Colorado (39.74°N,
 * 104.99°W) occurred ~124 minutes later (local solar time) than sunrise in
 * New York City (40.71°N, 74.01°W) — nearly identical latitudes, ~31°
 * longitude apart. Standard result of longitude difference × 4 min/degree.
 */
export const SUNRISE_TIME_DIFFERENCE_MINUTES: DomeReferenceCitation = {
  citationText: 'On 2024-03-20 (spring equinox), sunrise in Denver, Colorado (39.74°N, 104.99°W) occurred approximately 124 minutes later than sunrise in New York City (40.71°N, 74.01°W), measured in local solar time. The two cities are at nearly identical latitudes but differ by ~31° in longitude.',
  sourceRef: 'NOAA Solar Calculator / timeanddate.com, accessed 2024-03-20; coordinates from USGS GNIS; time difference calculated from longitude difference (30.98 deg x 4 min/deg = 123.92 min)',
  measuredValue: 124,
  unit: 'minutes',
  uncertainty: 2,
};

export const LONGITUDE_DIFFERENCE_DEGREES_DENVER_NYC = 30.98;

/**
 * During lunar eclipses, the radius of Earth's shadow on the Moon is
 * ~2.6x the radius of the Moon, consistently across eclipses regardless of
 * the Moon's position in the sky — Earth casts a circular shadow from every
 * viewing angle, the classical argument for sphericity (Aristotle, De Caelo
 * 297b, ~350 BCE), with the modern 2.6:1 ratio from NASA eclipse bulletins.
 */
export const EARTH_MOON_SHADOW_RATIO: DomeReferenceCitation = {
  citationText: 'During lunar eclipses, the radius of Earth\'s shadow on the Moon is approximately 2.6 times the radius of the Moon. This ratio is consistent across eclipses regardless of the Moon\'s position in the sky, indicating Earth casts a circular shadow from all viewing angles.',
  sourceRef: 'Aristotle, De Caelo 297b (~350 BCE) for the circular-shadow observation; NASA Eclipse Bulletins (Espenak & Meeus) for the 2.6:1 ratio; uncertainty reflects variation from Earth-Moon distance changes during eclipse',
  measuredValue: 2.6,
  unit: 'ratio',
  uncertainty: 0.2,
};
