/**
 * DOME WORLD — real, cited reference figures the model is judged against.
 *
 * Every value here is an independently-documented historical measurement or
 * standard geodesic derivation — never generated by `domeModel.ts`, never
 * adjusted to make either outcome come out a particular way. Adapted from an
 * external draft (Qwen); kept only the two citations that need no invented
 * mapping to compare against the model (see `domeModel.ts`'s module doc for
 * why the draft's star-altitude citation was dropped).
 */

export interface DomeReferenceCitation {
  readonly citationText: string;
  readonly sourceRef: string;
  readonly measuredValue: number;
  readonly unit: string;
  /** Half-width the citation itself is willing to stand behind — never invented for this comparison. */
  readonly uncertainty: number;
}

/**
 * Eratosthenes' shadow measurement (~240 BC): at summer solstice noon, the
 * sun was directly overhead at Syene (0° shadow) while a gnomon at
 * Alexandria, ~800 km away, cast a 7.2° shadow (1/50th of a circle).
 */
export const ERATOSTHENES_SHADOW_ANGLE: DomeReferenceCitation = {
  citationText: 'At Alexandria, ~800 km from Syene (where the sun was directly overhead), a gnomon cast a shadow of 7.2 degrees (1/50th of a circle) at summer solstice noon.',
  sourceRef: 'Eratosthenes via Cleomedes, De Motu Circulari Corporum Caelestium, Book 1 (~240 BC)',
  measuredValue: 7.2,
  unit: 'degrees',
  uncertainty: 0.5,
};

export const ERATOSTHENES_GROUND_DISTANCE_KM = 800;

/**
 * Standard geodesy: distance to the geometric horizon for an observer at
 * height h above a sphere of radius R is d = sqrt(2Rh + h^2). For h = 1.7 m
 * (average eye level) and R = 6371 km, d ~= 4.65 km — independently
 * confirmed by maritime observation (ships going hull-down at this range).
 */
export const HORIZON_DISTANCE_1_7M: DomeReferenceCitation = {
  citationText: 'Distance to the geometric horizon for an observer at 1.7 m height on a sphere of radius 6371 km, via d = sqrt(2Rh + h^2); confirmed by maritime hull-down observation.',
  sourceRef: 'Standard geodesy formula d = sqrt(2Rh + h^2), R = 6371 km, h = 1.7 m',
  measuredValue: 4.65,
  unit: 'km',
  uncertainty: 0.2,
};

export const HORIZON_OBSERVER_HEIGHT_M = 1.7;
