import { GENESIS_EVENT_CONTRACT_VERSION, type GenesisEvent } from '../../events/genesisEvent';
import { canonicalJson, fnv1a } from '../../events/hash';
import { executeIntervention } from '../bridge/worldFrameState';
import { spawnEntity } from '../ecs/entityFactory';
import { entityId, type EntityId } from '../ecs/types';
import { WorldGraph } from '../ecs/worldGraph';
import type { TemporalEngine } from '../temporal/temporalEngine';
import { mulberry32, type WorldBlueprint, type WorldBlueprintNode } from './worldBlueprint';

/**
 * WORLD GENERATOR — the ONLY code that turns a `WorldBlueprint` into a real
 * `WorldGraph`. Reuses `spawnEntity`/`WorldGraph.addRelationship` exactly as
 * any hand-written domain builder (chemistryKinetics.ts et al.) already
 * does — a generated world is not a second kind of world, it is the SAME
 * `WorldGraph` a builder function produces, just built from declarative
 * data instead of imperative calls.
 */
export interface GeneratedWorld {
  graph: WorldGraph;
  worldId: string;
  seed: number;
  /** Every entity id the generator created, in deterministic (depth-first, blueprint-order) creation order — the same order every time for the same blueprint. */
  entityIds: readonly EntityId[];
  /**
   * `world.generation.completed` — real provenance for how this world came
   * to exist, ready to record via `engine.journal.recordEvent(...)` once a
   * `TemporalEngine` wraps this graph (generation itself has no engine/tick
   * yet, so the caller records it, exactly like any other pre-tick-0 setup).
   */
  generationEvent: GenesisEvent;
}

/** Deterministically generates a world from `blueprint`. Same blueprint (seed included) in -> canonically identical `WorldGraph` out, always. */
export function generateWorld(blueprint: WorldBlueprint): GeneratedWorld {
  const graph = new WorldGraph();
  const rng = mulberry32(blueprint.seed);
  const entityIds: EntityId[] = [];

  spawnNode(graph, blueprint.root, undefined, rng, entityIds);

  for (const relationship of blueprint.relationships ?? []) {
    graph.addRelationship(entityId(relationship.from), entityId(relationship.to), relationship.kind);
  }

  // Structured provenance beyond seed/entityCount: WHICH templates were
  // requested and at WHAT level of detail — only present when this blueprint
  // came from `compileSpecification` (a hand-authored blueprint has neither
  // field, and the event's parameters correspondingly omit them, exactly as
  // before these fields existed on WorldBlueprint). Included in the same
  // reproducibility hash as worldId/seed/entityCount: two specifications
  // that differ only in requested templates or level of detail are a
  // genuinely different generation request and must not share a paramsHash.
  const templateProvenance = {
    ...(blueprint.templateIds !== undefined ? { templateIds: blueprint.templateIds } : {}),
    ...(blueprint.levelOfDetail !== undefined ? { levelOfDetail: blueprint.levelOfDetail } : {}),
  };
  const paramsHash = fnv1a(canonicalJson({ worldId: blueprint.worldId, seed: blueprint.seed, entityCount: entityIds.length, ...templateProvenance }));
  const generationEvent: GenesisEvent = {
    contractVersion: GENESIS_EVENT_CONTRACT_VERSION,
    id: `world-gen:${blueprint.worldId}:${blueprint.seed}`,
    type: 'world.generation.completed',
    timestamp: 0,
    source: blueprint.root.ref,
    affectedEntities: [blueprint.root.ref],
    cause: 'declarative-world-generation',
    parameters: { worldId: blueprint.worldId, seed: blueprint.seed, entityCount: entityIds.length, ...templateProvenance },
    provenance: {
      origin: 'experiment-action',
      seed: blueprint.seed,
      paramsHash,
      notes: blueprint.provenanceNote ?? 'Generated by WorldGenerator from a declarative WorldBlueprint.',
    },
  };

  return { graph, worldId: blueprint.worldId, seed: blueprint.seed, entityIds, generationEvent };
}

function spawnNode(graph: WorldGraph, node: WorldBlueprintNode, parentEntityId: EntityId | undefined, rng: () => number, entityIds: EntityId[]): EntityId {
  const id = spawnEntity(graph, {
    ref: node.ref,
    label: node.label,
    scaleLevel: node.scaleLevel,
    parentEntityId,
    spatial: node.spatial,
    physics: node.physics,
    chemical: node.chemical,
    domainBinding: node.domainBinding,
    domainState: node.domainState,
    statusLabel: node.statusLabel,
    grounding: node.grounding,
  });
  entityIds.push(id);

  for (const child of node.children ?? []) spawnNode(graph, child, id, rng, entityIds);

  const generated = node.generateChildren;
  if (generated) {
    for (let i = 0; i < generated.count; i++) {
      const jitter = generated.positionJitter;
      // Two PRNG draws per generated child (x then z) — always consumed in this fixed order,
      // even when a caller ends up discarding one, so the sequence position of every LATER draw
      // in this blueprint stays identical across otherwise-identical runs.
      const dx = jitter ? (rng() * 2 - 1) * jitter.radius : 0;
      const dz = jitter ? (rng() * 2 - 1) * jitter.radius : 0;
      const childId = spawnEntity(graph, {
        ref: { kind: generated.refKind, id: `${generated.refIdPrefix}${i}` },
        label: `${generated.label} ${i}`,
        scaleLevel: generated.scaleLevel,
        parentEntityId: id,
        spatial: jitter ? { position: { x: jitter.base.x + dx, y: jitter.base.y, z: jitter.base.z + dz } } : undefined,
        domainBinding: generated.domainBinding,
        physics: generated.physics,
        grounding: generated.grounding,
      });
      entityIds.push(childId);
    }
  }

  return id;
}

/**
 * Applies every `WorldBlueprintIntervention` declared for exactly
 * `engine.tick`, via the existing `executeIntervention` bridge call — never
 * a second intervention mechanism. A scenario runner calls this once per
 * tick (or at least whenever it might have just reached a declared
 * `atTick`); interventions for ticks already passed are simply skipped, not
 * retroactively applied.
 */
export function applyDueInterventions(engine: TemporalEngine, blueprint: WorldBlueprint): number {
  const due = (blueprint.interventions ?? []).filter((i) => i.atTick === engine.tick);
  for (const intervention of due) {
    executeIntervention(engine, entityId(intervention.target), intervention.parameters);
  }
  return due.length;
}
