import type { DeterministicPort, ProvenanceRef } from '../contracts';
import type { HumanDigitalTwinManifest, HumanHierarchyNode } from './humanHierarchy';
export function createReferenceHumanManifest(d:DeterministicPort):HumanDigitalTwinManifest{const p:readonly ProvenanceRef[]=[{sourceId:'GENESIS_REFERENCE_ANATOMY_MODEL',sourceType:'MODEL',version:'v7-transfer'}]; const nodes:HumanHierarchyNode[]=[
{nodeId:'human',parentId:null,level:'BODY',label:'Human body',nominalSizeM:1.75,position:[0,0,0],modelAssetId:'human-body',epistemicStatus:'MODEL',confidence:0.85,resolutionM:0.01,provenance:p,metadata:{}},
{nodeId:'cardiovascular',parentId:'human',level:'ORGAN_SYSTEM',label:'Cardiovascular system',nominalSizeM:1.2,position:[0,0.2,0],modelAssetId:'cardiovascular-system',epistemicStatus:'MODEL',confidence:0.85,resolutionM:0.005,provenance:p,metadata:{}},
{nodeId:'heart',parentId:'cardiovascular',level:'ORGAN',label:'Heart',nominalSizeM:0.12,position:[-0.04,0.28,0.08],modelAssetId:'heart',epistemicStatus:'MODEL',confidence:0.9,resolutionM:0.001,provenance:p,metadata:{}},
{nodeId:'myocardium',parentId:'heart',level:'TISSUE',label:'Myocardium',nominalSizeM:0.02,position:[0,0,0],modelAssetId:'myocardium',epistemicStatus:'RECONSTRUCTED',confidence:0.75,resolutionM:0.0001,provenance:p,metadata:{}},
{nodeId:'cardiomyocyte',parentId:'myocardium',level:'CELL',label:'Cardiomyocyte',nominalSizeM:0.0001,position:[0,0,0],modelAssetId:'cardiomyocyte',epistemicStatus:'MODEL',confidence:0.7,resolutionM:0.00001,provenance:p,metadata:{}},
{nodeId:'mitochondrion',parentId:'cardiomyocyte',level:'ORGANELLE',label:'Mitochondrion',nominalSizeM:0.000002,position:[0,0,0],modelAssetId:'mitochondrion',epistemicStatus:'MODEL',confidence:0.65,resolutionM:0.0000002,provenance:p,metadata:{}},
{nodeId:'atp-synthase',parentId:'mitochondrion',level:'MOLECULE',label:'ATP synthase complex',nominalSizeM:0.000000015,position:[0,0,0],modelAssetId:'atp-synthase',epistemicStatus:'MODEL',confidence:0.6,resolutionM:0.000000001,provenance:p,metadata:{representation:'coarse molecular model'}},
]; const core={manifestId:'reference-human-v7',subjectKind:'GENERIC_REFERENCE' as const,nodes,limitations:['Reference model, not patient-specific medical data.','Macro-to-micro transitions may mix model and reconstructed representations; epistemic labels must remain visible.']}; return {...core,fingerprint:d.fingerprint(core)};}
