import type { CanonicalVisualRuntimePort, DeterministicPort, EvidenceSink, VisualEntityState } from '../contracts';
import { emitStageEvidence } from '../evidence';
import { createReferenceHumanManifest } from './humanManifest';
import { validateHierarchyScaleMonotonicity } from './humanLod';
import { HyperscopeNavigator } from './hyperscopeNavigator';
import { epistemicOverlay } from './provenanceLabels';
export interface MacroMicroResult { readonly manifestFingerprint:string; readonly transitionFingerprints:readonly string[]; readonly terminalNodeId:string; readonly overlayFingerprint:string }
export function runMacroMicroJourney(args:{readonly deterministic:DeterministicPort;readonly evidence:EvidenceSink;readonly visual:CanonicalVisualRuntimePort;readonly targetNodeId:string}):MacroMicroResult{const manifest=createReferenceHumanManifest(args.deterministic); if(!validateHierarchyScaleMonotonicity(manifest.nodes)) throw new Error('Human hierarchy scale monotonicity failed'); const nav=new HyperscopeNavigator(manifest); const path=nav.pathTo(args.targetNodeId); if(path.length<2) throw new Error('Macro-micro target path too short'); const transitionFingerprints:string[]=[]; for(let i=0;i<path.length;i+=1){const node=path[i]; if(!node) continue; const entity:VisualEntityState={entityId:node.nodeId,kind:`human:${node.level.toLowerCase()}`,position:node.position,scale:[1,1,1],labels:{label:node.label,level:node.level,epistemicStatus:node.epistemicStatus,modelAssetId:node.modelAssetId},scalarState:{nominalSizeM:node.nominalSizeM,resolutionM:node.resolutionM,confidence:node.confidence},visible:i===path.length-1}; args.visual.upsertEntity(entity); if(i>0){const prev=path[i-1]; if(!prev) throw new Error('previous path node missing'); const step=nav.descend(prev.nodeId,node.nodeId); if(!step.allowed) throw new Error(`Invalid hyperscope transition ${prev.nodeId}->${node.nodeId}`); transitionFingerprints.push(args.deterministic.fingerprint(step));}}
 const terminal=path[path.length-1]; if(!terminal) throw new Error('terminal node missing'); const overlay=epistemicOverlay(terminal); const result={manifestFingerprint:manifest.fingerprint,transitionFingerprints,terminalNodeId:terminal.nodeId,overlayFingerprint:args.deterministic.fingerprint(overlay)}; emitStageEvidence({sink:args.evidence,deterministic:args.deterministic,type:'HYPERSCOPE_MACRO_MICRO_COMPLETED',stage:'V7',modelId:'human-macro-micro-v7',input:{targetNodeId:args.targetNodeId},result,epistemicStatus:'MODEL',evidenceClass:'MODEL',provenance:terminal.provenance}); return result;}
