import type { EntityRef } from '../../events/genesisEvent';

/**
 * WORLD GENERATION — STRUCTURAL GEOMETRY COMPONENT.
 *
 * `GeometryComponent` is ONE new optional ECS component — added to the
 * existing `WorldModelEntity`/`EntityBlueprint`/`WorldBlueprintNode` shape
 * exactly the way `spatial`/`physics`/`chemical`/`domainBinding` already
 * are (see ecs/types.ts) — NOT a second entity ontology and NOT a second
 * world graph. Every district/road/building/room/door/stair/nav-node
 * generated by the geometry pipeline (generation/geometry/) is a normal
 * `WorldModelEntity` living in the SAME canonical `WorldGraph`, simply
 * carrying this component in addition to (or instead of) `spatial`.
 *
 * Connectivity that needs a data payload beyond a label (a door's two
 * sides, a stair's two floors, a navigation edge's cost) is modeled as
 * fields INSIDE this component (`fromRef`/`toRef`, `connectsFloorRefs`,
 * ...), never as a `WorldGraph.EntityRelationship` — that type is
 * deliberately payload-free (`{from,to,kind}`) and stays that way; see
 * ecs/worldGraph.ts's own doc on `EntityRelationship`.
 */

export interface Bounds2D {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
}

export function boundsWidth(b: Bounds2D): number {
  return b.maxX - b.minX;
}

export function boundsDepth(b: Bounds2D): number {
  return b.maxZ - b.minZ;
}

export function boundsAreaM2(b: Bounds2D): number {
  return Math.max(0, boundsWidth(b)) * Math.max(0, boundsDepth(b));
}

export function boundsCenter(b: Bounds2D): { x: number; z: number } {
  return { x: (b.minX + b.maxX) / 2, z: (b.minZ + b.maxZ) / 2 };
}

export function boundsContainsPoint(b: Bounds2D, x: number, z: number): boolean {
  return x >= b.minX && x <= b.maxX && z >= b.minZ && z <= b.maxZ;
}

/** True for two bounds that overlap by more than a shared edge (strict interior overlap). */
export function boundsOverlap(a: Bounds2D, b: Bounds2D): boolean {
  return a.minX < b.maxX && a.maxX > b.minX && a.minZ < b.maxZ && a.maxZ > b.minZ;
}

export type DistrictType = 'RESIDENTIAL' | 'COMMERCIAL' | 'INDUSTRIAL' | 'CIVIC' | 'PARK' | 'SCIENTIFIC' | 'MIXED_USE';

export type BuildingType =
  | 'RESIDENTIAL'
  | 'COMMERCIAL'
  | 'INDUSTRIAL'
  | 'CIVIC'
  | 'HOSPITAL'
  | 'LABORATORY'
  | 'BIOLOGY_LAB'
  | 'CHEMISTRY_LAB'
  | 'IMAGING_CENTER'
  | 'MICROSCOPY_CENTER'
  | 'RESEARCH_CAMPUS'
  | 'BIOMEDICAL_CENTER'
  | 'WATER_RESEARCH_FACILITY';

export type RoomType =
  | 'LOBBY'
  | 'CORRIDOR'
  | 'OFFICE'
  | 'STORAGE'
  | 'MECHANICAL'
  | 'RESIDENTIAL_UNIT'
  | 'RETAIL_FLOOR'
  | 'WAREHOUSE_FLOOR'
  | 'WARD'
  | 'LAB_BENCH_ROOM'
  | 'IMAGING_SUITE'
  | 'MICROSCOPY_SUITE'
  | 'REACTOR_ROOM'
  | 'PUMP_ROOM'
  | 'MATERIALS_LAB'
  | 'GENERIC';

export type NavigationMode = 'WALK' | 'DRIVE' | 'STAIR' | 'ELEVATOR';

export interface DistrictGeometry {
  kind: 'DISTRICT';
  bounds: Bounds2D;
  districtType: DistrictType;
}

export type RoadClass = 'ARTERIAL' | 'LOCAL';

export interface RoadGeometry {
  kind: 'ROAD';
  start: { x: number; z: number };
  end: { x: number; z: number };
  widthM: number;
  roadClass: RoadClass;
}

export interface IntersectionGeometry {
  kind: 'INTERSECTION';
  position: { x: number; z: number };
  connectedRoadRefs: readonly EntityRef[];
}

export interface ParcelGeometry {
  kind: 'PARCEL';
  bounds: Bounds2D;
  districtRef: EntityRef;
  frontageRoadRef?: EntityRef;
}

export interface BuildingGeometry {
  kind: 'BUILDING';
  bounds: Bounds2D;
  buildingType: BuildingType;
  floorCount: number;
  parcelRef: EntityRef;
  districtRef: EntityRef;
}

export interface FloorGeometry {
  kind: 'FLOOR';
  level: number;
  bounds: Bounds2D;
  heightM: number;
  buildingRef: EntityRef;
}

export interface RoomGeometry {
  kind: 'ROOM';
  bounds: Bounds2D;
  roomType: RoomType;
  floorRef: EntityRef;
  buildingRef: EntityRef;
}

export interface DoorGeometry {
  kind: 'DOOR';
  position: { x: number; z: number };
  fromRef: EntityRef;
  toRef: EntityRef;
}

/** Connects the SAME (x,z) position across two vertically adjacent floors of one building. */
export interface StairGeometry {
  kind: 'STAIR';
  position: { x: number; z: number };
  buildingRef: EntityRef;
  connectsFloorRefs: readonly [EntityRef, EntityRef];
}

/** Connects the SAME (x,z) position across every floor it serves (2+) of one building. */
export interface ElevatorGeometry {
  kind: 'ELEVATOR';
  position: { x: number; z: number };
  buildingRef: EntityRef;
  connectsFloorRefs: readonly EntityRef[];
}

export interface AssetSlotGeometry {
  kind: 'ASSET_SLOT';
  position: { x: number; z: number };
  roomRef: EntityRef;
  slotType: string;
  /** Data-layer only (non-negotiable #15): no real AssetRegistry/host exists yet, so this is not resolved to a mesh/prefab here — a future asset host is expected to consume `slotType` + `roomRef`. */
  occupantRef?: EntityRef;
}

export interface NavNodeGeometry {
  kind: 'NAV_NODE';
  position: { x: number; z: number };
  /** The entity this node sits inside/at (room, intersection, parcel frontage, ...) — informational, for query/debug only. */
  atRef?: EntityRef;
}

/** A real spatial-adjacency edge (non-negotiable #10) — never derived from array order. `costM` is straight-line distance between the two nodes' positions unless `mode` implies a fixed vertical traversal (STAIR/ELEVATOR). */
export interface NavEdgeGeometry {
  kind: 'NAV_EDGE';
  fromRef: EntityRef;
  toRef: EntityRef;
  costM: number;
  mode: NavigationMode;
}

export interface NavZoneGeometry {
  kind: 'NAV_ZONE';
  bounds: Bounds2D;
  walkable: boolean;
}

export interface SpawnPointGeometry {
  kind: 'SPAWN_POINT';
  position: { x: number; z: number };
  forKind?: string;
}

export interface ApproachPointGeometry {
  kind: 'APPROACH_POINT';
  position: { x: number; z: number };
  targetRef: EntityRef;
}

export interface InteractionPointGeometry {
  kind: 'INTERACTION_POINT';
  position: { x: number; z: number };
  targetRef: EntityRef;
  interactionKind: string;
}

export type GeometryComponent =
  | DistrictGeometry
  | RoadGeometry
  | IntersectionGeometry
  | ParcelGeometry
  | BuildingGeometry
  | FloorGeometry
  | RoomGeometry
  | DoorGeometry
  | StairGeometry
  | ElevatorGeometry
  | AssetSlotGeometry
  | NavNodeGeometry
  | NavEdgeGeometry
  | NavZoneGeometry
  | SpawnPointGeometry
  | ApproachPointGeometry
  | InteractionPointGeometry;
