export type VisualCapabilityStatus='NOT_IMPLEMENTED'|'STRUCTURAL'|'UNIT_VERIFIED'|'E2E_VERIFIED'|'REAL_BROWSER_VERIFIED';
export type VisualCapabilityId=
| 'V6_ROOM_SPEC'|'V6_ROOM_COMPILER'|'V6_ASSET_SLOTS'|'V6_INSTRUMENT_PLACEMENT'|'V6_WALKABLE_LAYOUT'|'V6_LIGHTING_PROFILE'|'V6_INTERACTION_TARGETS'|'V6_MICROSCOPE'|'V6_SPECTROMETER'|'V6_MATERIALS_STATION'|'V6_BIOLOGY_STATION'|'V6_COMPUTE_STATION'|'V6_PROVENANCE'|'V6_EVIDENCE'|'V6_DETERMINISM'|'V6_CANONICAL_WORLD_SEAM'|'V6_MULTI_ROOM_KIND'|'V6_CAPABILITY_DRIVEN_ASSETS'|'V6_ENTITY_LABELS'|'V6_REAL_SCALE_GEOMETRY_CONTRACT'
| 'V61_CAMERA_KEYFRAMES'|'V61_CAMERA_INTERPOLATION'|'V61_DOF'|'V61_EXPOSURE'|'V61_FOV'|'V61_CUT_RESET'|'V61_DISCONTINUITY_GUARD'|'V61_FRAME_SEQUENCER'|'V61_CAPTURE_MANIFEST'|'V61_CAPTURE_FINGERPRINT'|'V61_EVIDENCE'|'REAL_BROWSER_CANONICAL_CAPTURE'
| 'V7_HUMAN_MANIFEST'|'V7_BODY'|'V7_ORGAN_SYSTEM'|'V7_ORGAN'|'V7_TISSUE'|'V7_CELL'|'V7_ORGANELLE'|'V7_MOLECULE'|'V7_ORGAN_PICKING'|'V7_HYPERSCOPE'|'V7_SCALE_MONOTONICITY'|'V7_LOD'|'V7_EPISTEMIC_LABELS'|'V7_PROVENANCE'|'V7_CONFIDENCE'|'V7_RESOLUTION_METADATA'|'V7_EVIDENCE'|'V7_DETERMINISTIC_REPLAY';
export interface VisualCapabilityEntry{readonly capability:VisualCapabilityId;readonly status:VisualCapabilityStatus;readonly evidence:readonly string[]}
export interface VisualStageCapabilityReport{readonly entries:readonly VisualCapabilityEntry[];readonly e2eOrStrongerPercent:number;readonly realBrowserVerifiedPercent:number;readonly TRANSFER_SCOPE_98_E2E:boolean;readonly REAL_REPO_VISUAL_COMPLETE:boolean}
const ORDER:readonly VisualCapabilityStatus[]=['NOT_IMPLEMENTED','STRUCTURAL','UNIT_VERIFIED','E2E_VERIFIED','REAL_BROWSER_VERIFIED'];
const atLeast=(s:VisualCapabilityStatus,t:VisualCapabilityStatus)=>ORDER.indexOf(s)>=ORDER.indexOf(t);
export function buildVisualStageCapabilityReport(entries:readonly VisualCapabilityEntry[]):VisualStageCapabilityReport{if(entries.length!==50) throw new Error(`Expected exactly 50 capabilities, got ${entries.length}`); if(new Set(entries.map(e=>e.capability)).size!==50) throw new Error('Duplicate visual capability id'); const e2e=entries.filter(e=>atLeast(e.status,'E2E_VERIFIED')).length; const browser=entries.filter(e=>e.status==='REAL_BROWSER_VERIFIED').length; const e2eOrStrongerPercent=e2e/50*100; return {entries,e2eOrStrongerPercent,realBrowserVerifiedPercent:browser/50*100,TRANSFER_SCOPE_98_E2E:e2eOrStrongerPercent>=98,REAL_REPO_VISUAL_COMPLETE:entries.every(e=>e.status==='REAL_BROWSER_VERIFIED'||(e.capability!=='REAL_BROWSER_CANONICAL_CAPTURE'&&atLeast(e.status,'E2E_VERIFIED')))&&entries.find(e=>e.capability==='REAL_BROWSER_CANONICAL_CAPTURE')?.status==='REAL_BROWSER_VERIFIED'};}
