import { canonicalJson, fnv1a } from '../events/hash';
import { saveHypothesisLoopToMemory } from '../scienceMemory';
import type { SavedExperiment } from '../scienceMemory';
import {
  buildSavedHypothesisLoop,
  executePreregisteredHypothesesAsync,
  generateCompetingHypotheses,
  HYPOTHESIS_PROBLEMS,
  preregisterHypotheses,
  replaySavedHypothesisLoopAsync,
  selectNextHypothesisExperiment,
  type HypothesisLoopReplay,
  type HypothesisLoopResult,
  type HypothesisProblem,
  type NextHypothesisExperiment,
  type Preregistration,
  type SavedHypothesisLoop,
} from './hypothesisLoop';

/**
 * BELIEF-CHANGE RUN — the connecting layer this mission asked for.
 *
 * This is NOT a second Epistemic Engine, Replay engine, Evidence system or
 * hypothesis ontology. Every field below is either a direct reference to an
 * existing Genesis structure or a thin, read-only derivation from one:
 *
 *   hypotheses / predictions / preregistration -> `hypothesisLoop.ts`
 *     (`HypothesisProblem`, `Preregistration`, unchanged)
 *   real execution / observation / comparison  -> `hypothesisLoop.ts`
 *     (`executePreregisteredHypothesesAsync`, new in this mission, itself
 *     built on the existing `designScientificExperiment` +
 *     `executeScientificExperiment` / `executeScientificBackendExperiment`)
 *   epistemic update (before/after status)     -> `HypothesisLoopResult`
 *     (`HypothesisStatus`: HYPOTHESIS/PRE_REGISTERED/SUPPORTED/FALSIFIED/
 *     INCONCLUSIVE/BLOCKED/UNKNOWN — Genesis's existing status vocabulary,
 *     not a new one)
 *   next experiment / "what would change my mind" -> `hypothesisLoop.ts`
 *     (`selectNextHypothesisExperiment`, unchanged, already state-derived
 *     and domain-agnostic)
 *   evidence / provenance                      -> `HypothesisLoopResult.chains`
 *     / `.packs` / `.allRuns` (existing `ScientificEvidenceChain` /
 *     `ScientificEvidencePack` / `ExperimentRun.provenance`, unchanged)
 *   memory                                     -> `scienceMemory.ts`
 *     (`saveHypothesisLoopToMemory`, unchanged, already generic over any
 *     `HypothesisLoopResult`)
 *   replay                                     -> `hypothesisLoop.ts`
 *     (`replaySavedHypothesisLoopAsync`, new in this mission, returns the
 *     existing MATCH / DRIFT / BLOCKED vocabulary — no new replay protocol)
 *
 * `BeliefChangeRun` only adds the "WHY did science change?" structured
 * explanation, because nothing in the existing pieces produces that
 * specific BEFORE/OBSERVATION/PREDICTION/COMPARISON/AFTER shape — and even
 * that explanation is built EXCLUSIVELY by reading fields already present
 * on `HypothesisLoopResult`. No field here is computed from a template that
 * could diverge from the real recorded numbers.
 */
export const BELIEF_CHANGE_RUN_VERSION = '1.0.0';

export type BeliefChangeStatus =
  | 'RESOLVED'
  | 'RUNNING'
  | 'INCONCLUSIVE'
  | 'BLOCKED'
  | 'NO_USEFUL_EXPERIMENT';

export interface BeliefChangeHypothesisView {
  hypothesisId: string;
  statement: string;
  predictedOutcome: string;
  statusBefore: string;
  statusAfter: string;
  observedMetric: number | null;
  baselineMetric: number | null;
  unit: string | null;
  reason: string;
}

/**
 * The structured "why did my belief change" record. Every field is read
 * from `HypothesisLoopResult` — nothing here is generated by free text
 * inference. `reason` is a template filled ONLY with recorded values
 * (statements, predicted outcomes, observed metrics, discrimination
 * reasoning), so the same run always reproduces the same explanation.
 */
export interface BeliefChangeWhy {
  question: string;
  before: readonly { hypothesisId: string; statement: string; status: string }[];
  predictions: readonly { hypothesisId: string; predictedOutcome: string }[];
  observation: readonly { hypothesisId: string; metric: string; value: number | null; unit: string | null }[];
  comparison: string;
  after: readonly { hypothesisId: string; statement: string; status: string }[];
  reason: string;
}

export interface BeliefChangeRun {
  contractVersion: string;
  runId: string;
  question: string;
  problem: HypothesisProblem;
  preregistration: Preregistration;
  loopResult: HypothesisLoopResult;
  hypotheses: readonly BeliefChangeHypothesisView[];
  why: BeliefChangeWhy;
  nextExperiment: NextHypothesisExperiment;
  status: BeliefChangeStatus;
  /** Null only when the preregistration was violated — an unsafe record must never be persisted as memory. */
  saved: SavedHypothesisLoop | null;
}

function unitForHypothesis(loopResult: HypothesisLoopResult, hypothesisId: string): string | null {
  const outcome = loopResult.outcomes.find((entry) => entry.hypothesisId === hypothesisId);
  if (!outcome?.evidenceChainId) return null;
  const chain = loopResult.chains.find((entry) => entry.evidenceId === outcome.evidenceChainId);
  const variantArm = chain?.arms.find((arm) => arm.kind === 'variant');
  return variantArm?.units || null;
}

function statusBeforeMap(preregistration: Preregistration): ReadonlyMap<string, string> {
  return new Map(preregistration.hypotheses.map((hypothesis) => [hypothesis.hypothesisId, hypothesis.status]));
}

function buildWhy(question: string, preregistration: Preregistration, loopResult: HypothesisLoopResult): BeliefChangeWhy {
  const before = statusBeforeMap(preregistration);
  const beforeView = preregistration.hypotheses.map((hypothesis) => ({
    hypothesisId: hypothesis.hypothesisId, statement: hypothesis.statement, status: before.get(hypothesis.hypothesisId) ?? 'UNKNOWN',
  }));
  const predictions = preregistration.hypotheses.map((hypothesis) => ({ hypothesisId: hypothesis.hypothesisId, predictedOutcome: hypothesis.predictedOutcome }));
  const observation = loopResult.outcomes.map((outcome) => ({
    hypothesisId: outcome.hypothesisId, metric: loopResult.preregistration.set.problem.primaryMetric,
    value: outcome.observedMetric, unit: unitForHypothesis(loopResult, outcome.hypothesisId),
  }));
  const afterView = loopResult.outcomes.map((outcome) => {
    const hypothesis = preregistration.hypotheses.find((entry) => entry.hypothesisId === outcome.hypothesisId);
    return { hypothesisId: outcome.hypothesisId, statement: hypothesis?.statement ?? 'UNKNOWN', status: outcome.status };
  });

  const winner = loopResult.discrimination.winnerHypothesisId !== null
    ? loopResult.preregistration.hypotheses.find((entry) => entry.hypothesisId === loopResult.discrimination.winnerHypothesisId)
    : undefined;
  const winnerOutcome = winner ? loopResult.outcomes.find((entry) => entry.hypothesisId === winner.hypothesisId) : undefined;
  const others = loopResult.outcomes.filter((entry) => entry.hypothesisId !== winner?.hypothesisId);

  const reason = loopResult.discrimination.decisive && winner !== undefined && winnerOutcome !== undefined
    ? `Hipoteza "${winner.statement}" przewidywała: ${winner.predictedOutcome} Zmierzona wartość ${loopResult.preregistration.set.problem.primaryMetric} wyniosła ${winnerOutcome.observedMetric ?? 'brak'} (odniesienie ${winnerOutcome.baselineMetric ?? 'brak'}). ${loopResult.discrimination.reason} ${others.map((entry) => entry.reason).join(' ')}`.trim()
    : !loopResult.preregistrationIntact.intact
      ? loopResult.preregistrationIntact.reason
      : loopResult.outcomes.some((entry) => entry.status === 'BLOCKED')
        ? `Co najmniej jedna hipoteza jest BLOCKED: ${loopResult.outcomes.filter((entry) => entry.status === 'BLOCKED').map((entry) => entry.reason).join(' ')}`
        : loopResult.discrimination.reason;

  return { question, before: beforeView, predictions, observation, comparison: loopResult.discrimination.reason, after: afterView, reason };
}

function statusOf(loopResult: HypothesisLoopResult, nextExperiment: NextHypothesisExperiment): BeliefChangeStatus {
  if (!loopResult.preregistrationIntact.intact) return 'BLOCKED';
  if (loopResult.outcomes.some((entry) => entry.status === 'BLOCKED')) return 'BLOCKED';
  if (loopResult.outcomes.some((entry) => entry.status === 'INCONCLUSIVE')) return 'INCONCLUSIVE';
  if (loopResult.discrimination.decisive && nextExperiment.status === 'RESOLVED') return 'RESOLVED';
  if (nextExperiment.status === 'RESOLVED' && nextExperiment.request === null) return 'NO_USEFUL_EXPERIMENT';
  return 'RUNNING';
}

/**
 * Runs the full belief-change chain for one declared `HypothesisProblem`:
 * QUESTION -> COMPETING HYPOTHESES -> PREDICTIONS -> REAL EXECUTION ->
 * OBSERVATION -> COMPARISON -> EPISTEMIC UPDATE -> WHY -> NEXT EXPERIMENT.
 * Every step calls an existing, unmodified (or minimally extended)
 * Genesis function; this orchestrator adds no scientific computation.
 */
export async function runBeliefChangeRun(problemId: string): Promise<BeliefChangeRun> {
  const problem = HYPOTHESIS_PROBLEMS.find((entry) => entry.problemId === problemId);
  if (problem === undefined) {
    throw new Error(`Unknown belief-change problem "${problemId}" — it must be declared in HYPOTHESIS_PROBLEMS first.`);
  }
  const set = generateCompetingHypotheses(problem);
  const preregistration = preregisterHypotheses(set);
  const loopResult = await executePreregisteredHypothesesAsync(preregistration);
  const nextExperiment = selectNextHypothesisExperiment(loopResult);
  const why = buildWhy(problem.statement, preregistration, loopResult);
  const status = statusOf(loopResult, nextExperiment);
  const saved = loopResult.preregistrationIntact.intact ? buildSavedHypothesisLoop(loopResult) : null;

  const hypotheses: BeliefChangeHypothesisView[] = preregistration.hypotheses.map((hypothesis) => {
    const outcome = loopResult.outcomes.find((entry) => entry.hypothesisId === hypothesis.hypothesisId);
    return {
      hypothesisId: hypothesis.hypothesisId,
      statement: hypothesis.statement,
      predictedOutcome: hypothesis.predictedOutcome,
      statusBefore: hypothesis.status,
      statusAfter: outcome?.status ?? 'UNKNOWN',
      observedMetric: outcome?.observedMetric ?? null,
      baselineMetric: outcome?.baselineMetric ?? null,
      unit: unitForHypothesis(loopResult, hypothesis.hypothesisId),
      reason: outcome?.reason ?? 'Brak wykonanego wyniku dla tej hipotezy.',
    };
  });

  return {
    contractVersion: BELIEF_CHANGE_RUN_VERSION,
    runId: `belief_${fnv1a(canonicalJson({ preregistrationFingerprint: preregistration.preregistrationFingerprint, outcomes: loopResult.outcomes }))}`,
    question: problem.statement,
    problem,
    preregistration,
    loopResult,
    hypotheses,
    why,
    nextExperiment,
    status,
    saved,
  };
}

/** Persists the run's hypothesis loop into the existing Scientific Memory. Returns null when the preregistration was violated — an unsafe record must never be saved. */
export function saveBeliefChangeRunToMemory(run: BeliefChangeRun): SavedExperiment | null {
  if (run.saved === null) return null;
  return saveHypothesisLoopToMemory(run.loopResult);
}

export type BeliefChangeReplayStatus = HypothesisLoopReplay['status'];

export interface BeliefChangeReplay {
  status: BeliefChangeReplayStatus;
  reason: string;
  differences: HypothesisLoopReplay['differences'];
}

/**
 * Replays a `BeliefChangeRun` from its own saved hypothesis loop. Reuses
 * `replaySavedHypothesisLoopAsync` unchanged — MATCH/DRIFT/BLOCKED, never a
 * second replay protocol.
 */
export async function replayBeliefChangeRun(run: BeliefChangeRun): Promise<BeliefChangeReplay> {
  if (run.saved === null) {
    return { status: 'BLOCKED', reason: 'Nie można odtworzyć: prerejestracja tego przebiegu została naruszona przed zapisem.', differences: [] };
  }
  const replay = await replaySavedHypothesisLoopAsync(run.saved);
  return { status: replay.status, reason: replay.reason, differences: replay.differences };
}
