#!/usr/bin/env node
/**
 * GENESIS ASSET PIPELINE — Ambulance GLB Exporter
 * ==================================================
 *
 * Generates `public/assets/genesis-procedural/ambulance/ambulance.glb`: a REAL, valid, loadable
 * binary glTF asset — not a placeholder, not hand-written JSON — produced by building an actual
 * three.js scene and running it through three.js's own `GLTFExporter`. This is the "even if simple/
 * CC0/procedurally-generated-on-your-end" asset `graphics/assetPipeline.ts`'s `createAssetSlot` seam
 * needed to prove its fallback -> real-asset swap end to end, since Genesis has no external asset
 * pipeline (no network fetch of a third-party model) — see `assetGovernance.ts`'s own manifest for
 * why: every loaded asset needs verified source/license/checksum provenance, and this one's
 * provenance is simply "generated by this exact script, in this repo" (see its own manifest entry).
 *
 * The geometry deliberately mirrors `core/three/graphics/vehicleKit.ts`'s own `createVehicle('
 * ambulance', ...)` proportions (chassis/cabin/wheels/light-bar/red-cross) — same silhouette as the
 * procedural fallback it replaces, so the swap in `epidemicCity3D.ts` reads as "the same ambulance,
 * now with a real loaded asset" rather than a jarring shape change. It does NOT import vehicleKit.ts
 * directly (a plain Node script, no TypeScript toolchain in this repo's build) — the geometry is
 * reproduced directly against the `three` package, which this script depends on identically.
 *
 * Run with: node scripts/exportAmbulanceAsset.mjs
 * Re-run whenever the output needs regenerating — deterministic, no random seed, so re-running
 * without changing this script produces a byte-identical file (verified by
 * `assetPipelineAmbulanceSwap.test.ts`, which checks the committed file's own SHA-256 against the
 * value recorded in `assetGovernance.ts`).
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// GLTFExporter's binary/base64 output path uses the browser's `FileReader` API, which plain Node
// has no global for — a minimal polyfill over Node's own global `Blob.arrayBuffer()` is all
// `readAsArrayBuffer`/`readAsDataURL` actually need here.
class NodeFileReader {
  result = null;
  onloadend = null;
  onerror = null;
  readAsArrayBuffer(blob) {
    blob.arrayBuffer().then((buf) => { this.result = buf; this.onloadend?.(); }).catch((err) => this.onerror?.(err));
  }
  readAsDataURL(blob) {
    blob.arrayBuffer().then((buf) => {
      this.result = `data:${blob.type || 'application/octet-stream'};base64,${Buffer.from(buf).toString('base64')}`;
      this.onloadend?.();
    }).catch((err) => this.onerror?.(err));
  }
}
globalThis.FileReader = NodeFileReader;

const THREE = await import('three');
const { GLTFExporter } = await import('three/examples/jsm/exporters/GLTFExporter.js');

const outDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../public/assets/genesis-procedural/ambulance');
const outFile = path.join(outDir, 'ambulance.glb');

function buildAmbulance() {
  const group = new THREE.Group();
  group.name = 'genesis-procedural-ambulance';

  const width = 0.20;
  const length = 0.54;
  const height = 0.22;
  const cabinHeight = 0.19;
  const wheelRadius = 0.05;

  const bodyMaterial = new THREE.MeshStandardMaterial({ color: 0xf2f4f6, roughness: 0.35, metalness: 0.2 });
  const glassMaterial = new THREE.MeshStandardMaterial({ color: 0x1c2733, roughness: 0.22, metalness: 0.35 });
  const wheelMaterial = new THREE.MeshStandardMaterial({ color: 0x14171c, roughness: 0.75, metalness: 0.1 });
  const lightMaterial = new THREE.MeshStandardMaterial({ emissive: 0xffffff, emissiveIntensity: 0.2, color: 0x222222, roughness: 0.4 });
  const crossMaterial = new THREE.MeshBasicMaterial({ color: 0xff3b3b });

  const chassis = new THREE.Mesh(new THREE.BoxGeometry(width, height, length), bodyMaterial);
  chassis.position.y = wheelRadius + height / 2;
  group.add(chassis);

  const cabinLength = length * 0.62;
  const cabin = new THREE.Mesh(new THREE.BoxGeometry(width * 0.92, cabinHeight, cabinLength), glassMaterial);
  cabin.position.set(0, wheelRadius + height + cabinHeight / 2, -length * 0.06);
  group.add(cabin);

  const wheelGeometry = new THREE.CylinderGeometry(wheelRadius, wheelRadius, width * 0.12, 12);
  const axleX = width / 2 - width * 0.02;
  const axleZ = length / 2 - wheelRadius * 1.3;
  for (const dx of [-axleX, axleX]) {
    for (const dz of [-axleZ, axleZ]) {
      const wheel = new THREE.Mesh(wheelGeometry, wheelMaterial);
      wheel.rotation.z = Math.PI / 2;
      wheel.position.set(dx, wheelRadius, dz);
      group.add(wheel);
    }
  }

  const bar = new THREE.Mesh(new THREE.BoxGeometry(width * 0.7, 0.02, 0.05), lightMaterial);
  bar.position.set(0, wheelRadius + height + cabinHeight + 0.02, -length * 0.06);
  group.add(bar);

  const crossH = new THREE.Mesh(new THREE.BoxGeometry(width * 0.5, 0.03, 0.005), crossMaterial);
  const crossV = new THREE.Mesh(new THREE.BoxGeometry(width * 0.16, 0.09, 0.005), crossMaterial);
  crossH.position.set(0, wheelRadius + height * 0.6, length / 2 + 0.003);
  crossV.position.copy(crossH.position);
  group.add(crossH, crossV);

  return group;
}

async function main() {
  const scene = buildAmbulance();
  const exporter = new GLTFExporter();
  const glb = await new Promise((resolve, reject) => {
    exporter.parse(scene, resolve, reject, { binary: true, embedImages: true, forceIndices: true });
  });
  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, Buffer.from(glb));
  console.log(`Wrote ${outFile} (${(glb.byteLength / 1024).toFixed(1)} KB)`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
