import { fnv1a } from '../events/hash';
import { entityId, type WorldModelEntity } from '../worldModel/ecs/types';
import type { WorldGraph } from '../worldModel/ecs/worldGraph';
import type { BuildingType } from '../worldModel/ecs/geometry';
import type { StructuralDetailSpec } from '../worldModel/generation/geometry/structuralDetailSpec';
import type { WorldSpecification } from '../worldModel/specification/worldSpecification';
import { resolveEraProfile } from './historicalEra';

/** Canonical place/year -> WorldSpecification parameterization. V6 adds an opt-in interior flag. */
const PLACE_CITY_SIZE_MIN_M = 400;
const PLACE_CITY_SIZE_MAX_M = 900;
const PLACE_DISTRICT_COUNT_MIN = 3;
const PLACE_DISTRICT_COUNT_MAX = 6;
const PLACE_PARCELS_PER_DISTRICT_MIN = 3;
const PLACE_PARCELS_PER_DISTRICT_MAX = 6;

function hashToUnitInterval(input: string): number {
  return parseInt(fnv1a(input), 16) / 0xffffffff;
}

export interface PlaceGeographyProfile {
  readonly citySizeM: number;
  readonly districtCount: number;
  readonly parcelsPerDistrict: number;
  readonly seed: number;
}

export function resolvePlaceGeography(place: string): PlaceGeographyProfile {
  const normalized = place.trim().toLowerCase();
  const u1 = hashToUnitInterval(`${normalized}:citySize`);
  const u2 = hashToUnitInterval(`${normalized}:districtCount`);
  const u3 = hashToUnitInterval(`${normalized}:parcelsPerDistrict`);
  return {
    citySizeM: Math.round(PLACE_CITY_SIZE_MIN_M + u1 * (PLACE_CITY_SIZE_MAX_M - PLACE_CITY_SIZE_MIN_M)),
    districtCount: PLACE_DISTRICT_COUNT_MIN + Math.floor(u2 * (PLACE_DISTRICT_COUNT_MAX - PLACE_DISTRICT_COUNT_MIN + 1)),
    parcelsPerDistrict: PLACE_PARCELS_PER_DISTRICT_MIN + Math.floor(u3 * (PLACE_PARCELS_PER_DISTRICT_MAX - PLACE_PARCELS_PER_DISTRICT_MIN + 1)),
    seed: parseInt(fnv1a(`${normalized}:seed`), 16),
  };
}

export interface HistoricalWorldRequest {
  readonly place: string;
  readonly year: number;
  readonly generateNavigation?: boolean;
  /** V6: compile real FLOOR/ROOM/ASSET_SLOT geometry into the same WorldGraph. */
  readonly generateInteriors?: boolean;
  /** Facilities explicitly required by a product preset, generated by the canonical geometry pipeline. */
  readonly requiredBuildingTypes?: readonly BuildingType[];
}

export function historicalWorldId(place: string, year: number): string {
  return `historical:${place.trim().toLowerCase().replace(/\s+/g, '-')}:${year}`;
}

export function buildHistoricalWorldSpecification(request: HistoricalWorldRequest): WorldSpecification {
  const geography = resolvePlaceGeography(request.place);
  const era = resolveEraProfile(request.year);
  const structuralDetail: StructuralDetailSpec = {
    citySizeM: geography.citySizeM,
    districtCount: geography.districtCount,
    parcelsPerDistrict: geography.parcelsPerDistrict,
    maxFloors: era.maxFloors,
    generateInteriors: request.generateInteriors ?? false,
    generateNavigation: request.generateNavigation ?? false,
    requiredBuildingTypes: request.requiredBuildingTypes,
  };

  return {
    worldId: historicalWorldId(request.place, request.year),
    seed: geography.seed,
    worldType: ['CITY'],
    scale: 'MACRO_CITY',
    structuralDetail,
    provenanceNote: `Procedural era heuristic (${era.label}, cap ${era.maxFloors} floors) for "${request.place}" in ${request.year} — NOT a real historical reconstruction; no historical dataset backs this world. See historicalEra.ts.`,
  };
}

const PEDESTRIANS_PER_ROAD_MIN = 4;
const PEDESTRIANS_PER_ROAD_MAX = 8;
/** Perpendicular sidewalk offset from a road's centerline, in metres. */
const PEDESTRIAN_SIDEWALK_OFFSET_M = 2.2;

/**
 * Deterministic pedestrian presence for a generated historical CITY world. This is the SAME
 * canonical WorldModelEntity/WorldGraph contract every generated entity already uses (see
 * generation/geometry/index.ts) — no second world, no population solver, no new geometry kind.
 * `ref.kind: 'human'` is the ALREADY-canonical marker `personLike()` checks in
 * temporalCinematicVisualResolver.ts, so the resolver's existing hero/detailed(LOD1)/proxy(LOD2)
 * tiers apply completely unchanged; this only supplies the entities that were previously never
 * generated for a CITY template (unlike EPIDEMIOLOGY's single aggregate `population` entity, real
 * spatially-placed individuals are what the renderer's LOD system needs).
 *
 * This is deliberate scenic placement along each generated road's sidewalk offset — NOT
 * demographic or epidemiological modeling. Same honesty regime as this file's own
 * `provenanceNote`: grounding is `PROCEDURAL_APPROXIMATION` (a generic placement heuristic, no
 * domain solver), and the label says "Pedestrian", never a claim of a real historical person.
 */
export function populateHistoricalPedestrians(graph: WorldGraph, worldId: string): number {
  const roads = graph.listEntities().filter((e) => e.geometry?.kind === 'ROAD');
  let added = 0;
  for (const road of roads) {
    if (road.geometry?.kind !== 'ROAD') continue;
    const { start, end } = road.geometry;
    const dx = end.x - start.x;
    const dz = end.z - start.z;
    const length = Math.hypot(dx, dz);
    if (length < 1) continue;
    const nx = -dz / length;
    const nz = dx / length;
    const countU = hashToUnitInterval(`${worldId}:${road.id}:pedestrianCount`);
    const count = PEDESTRIANS_PER_ROAD_MIN + Math.floor(countU * (PEDESTRIANS_PER_ROAD_MAX - PEDESTRIANS_PER_ROAD_MIN + 1));
    for (let i = 0; i < count; i += 1) {
      const alongU = hashToUnitInterval(`${worldId}:${road.id}:pedestrian${i}:along`);
      const sideU = hashToUnitInterval(`${worldId}:${road.id}:pedestrian${i}:side`);
      const t = 0.08 + alongU * 0.84;
      const side = sideU < 0.5 ? -1 : 1;
      const ref = { kind: 'human', id: `${road.id}-pedestrian-${i}` };
      const id = entityId(ref);
      if (graph.has(id)) continue;
      const entity: WorldModelEntity = {
        id,
        ref,
        label: 'Pedestrian',
        scale: { level: 'DISTRICT' },
        spatial: {
          position: {
            x: start.x + dx * t + nx * PEDESTRIAN_SIDEWALK_OFFSET_M * side,
            y: 0,
            z: start.z + dz * t + nz * PEDESTRIAN_SIDEWALK_OFFSET_M * side,
          },
        },
        grounding: 'PROCEDURAL_APPROXIMATION',
        updatedAtTick: 0,
      };
      graph.addEntity(entity);
      added += 1;
    }
  }
  return added;
}
