/**
 * AUTONOMOUS MODEL GENERATION — real falsification by computation.
 *
 * `generatedSpacetimeHypotheses.ts` demonstrates generation-by-combination
 * over textual constraints, and discloses honestly that it can never
 * FALSIFY a candidate (it cannot detect logical contradiction). This module
 * demonstrates the complementary, stronger case the mission asked for:
 * KNOWN_EQUATION_TRANSFORMATION, where a generated candidate model is
 * tested against a REAL computed value and can genuinely fail.
 *
 * THE GENERATION: two already-declared, real models
 * (SR_TIME_DILATION_MODEL, GR_TIME_DILATION_MODEL from spacetimeModels.ts)
 * each output one scalar for the same GPS orbit. A generator with no
 * further physics knowledge can construct a small, enumerable family of
 * ways to COMPOSE two scalars into one predicted net effect — this module
 * builds two: the signed difference, and the quadrature sum. Composing
 * known model outputs into a new candidate relationship is exactly
 * "known-equation transformation" from the mission's generation-strategy
 * list, done without inventing new physics.
 *
 * THE TEST: each composed candidate's predicted value is compared against
 * the REAL, independently established reference — the net fractional rate
 * `runRelativisticTimeDilationCase()` actually derives from the correct,
 * textbook formula (GR excess minus SR deficit). This is not a fabricated
 * measurement: it is one real derivation checked against another real
 * derivation, and the residual is computed, not asserted.
 *
 *   LINEAR_DIFFERENCE candidate reproduces the reference formula exactly
 *   -> genuinely SUPPORTED.
 *   QUADRATURE_SUM candidate is a real alternative mathematical structure
 *   that, for this orbit's non-degenerate SR/GR magnitudes, does NOT equal
 *   the reference -> genuinely FALSIFIED, by computation, not by assertion.
 *
 * Neither result is a scientific discovery: SUPPORTED here means "matches
 * the already-established formula", not "confirmed by new evidence".
 */
import { checkGeneratedHypothesis, formalizeGeneratedHypothesis, testGeneratedHypothesis, type GeneratedHypothesis, type GeneratedHypothesisDraft, type HypothesisGenerationReplay } from '../hypothesisGeneration';
import { runRelativisticTimeDilationCase, type RelativisticTimeDilationResult } from './relativisticTimeDilation';
import { GR_TIME_DILATION_MODEL, SR_TIME_DILATION_MODEL } from './spacetimeModels';
import { saveExperiment, type SavedExperiment } from '../../scienceMemory';

export const GENERATED_PHYSICS_MODEL_CANDIDATES_VERSION = '1.0.0';

export type CompositionRule = 'LINEAR_DIFFERENCE' | 'QUADRATURE_SUM';

export const COMPOSITION_RULES: readonly CompositionRule[] = ['LINEAR_DIFFERENCE', 'QUADRATURE_SUM'];

/** Absolute tolerance on the net fractional rate — this quantity is of order 1e-10 for the GPS case, so 1e-15 is a tight, real bar, not a loose one that would let a wrong candidate through. */
export const COMPOSITION_TOLERANCE = 1e-15;

export function computeComposition(rule: CompositionRule, srDeficit: number, grExcess: number): number {
  if (rule === 'LINEAR_DIFFERENCE') return grExcess - srDeficit;
  return Math.sqrt(grExcess * grExcess + srDeficit * srDeficit);
}

function ruleDescription(rule: CompositionRule): string {
  return rule === 'LINEAR_DIFFERENCE'
    ? 'the signed difference (GR excess minus SR deficit)'
    : 'the quadrature sum (sqrt(GR excess^2 + SR deficit^2))';
}

function buildCandidate(rule: CompositionRule, reference: RelativisticTimeDilationResult): GeneratedHypothesis {
  const predicted = computeComposition(rule, reference.specialRelativisticFractionalDeficit, reference.gravitationalFractionalExcess);

  const draft: GeneratedHypothesisDraft = {
    hypothesisId: `gen_gps_composition_${rule.toLowerCase()}`,
    domainId: 'PHYSICS',
    statement: `The net fractional clock-rate difference for the GPS orbit equals ${ruleDescription(rule)} of the two known weak-field effects.`,
    strategy: 'KNOWN_EQUATION_TRANSFORMATION',
    dependencyIds: [SR_TIME_DILATION_MODEL.modelId, GR_TIME_DILATION_MODEL.modelId],
    assumptions: [
      'Both component models (SR fractional deficit, GR fractional excess) are independently valid at this order for this orbit.',
      `The composition rule under test (${rule}) is assumed to be the complete relationship — no cross term or higher-order correction is considered.`,
    ],
    generationRationale: `Generated by KNOWN_EQUATION_TRANSFORMATION: composing the declared outputs of "${SR_TIME_DILATION_MODEL.modelId}" and "${GR_TIME_DILATION_MODEL.modelId}" via the ${rule} rule, one of a small enumerable family of ways to combine two known scalar model outputs without introducing new physics.`,
    expectedPrediction: `Predicted net fractional rate = ${predicted.toExponential(6)}.`,
    falsificationCriteria: `Falsified if this composition's predicted value does not match, within an absolute tolerance of ${COMPOSITION_TOLERANCE}, the net fractional rate independently derived by the established GPS time-dilation case — a real, separately computed reference value, not this candidate's own assumption.`,
    requiredComputation: [`${SR_TIME_DILATION_MODEL.modelId} evaluation`, `${GR_TIME_DILATION_MODEL.modelId} evaluation`, `${rule} composition`],
    requiredData: [],
    provenance: ['strategy:KNOWN_EQUATION_TRANSFORMATION', `model:${SR_TIME_DILATION_MODEL.modelId}`, `model:${GR_TIME_DILATION_MODEL.modelId}`, `compositionRule:${rule}`],
  };

  let candidate = formalizeGeneratedHypothesis(draft);
  candidate = checkGeneratedHypothesis(candidate, () => ({ ok: true, reason: `Both dependency model ids are declared in spacetimeModels.ts (${SR_TIME_DILATION_MODEL.modelId}, ${GR_TIME_DILATION_MODEL.modelId}).` }));
  candidate = testGeneratedHypothesis(candidate, () => {
    const residual = Math.abs(predicted - reference.netFractionalRate);
    if (residual <= COMPOSITION_TOLERANCE) {
      return {
        verdict: 'SUPPORTED',
        reasoning: `Predicted ${predicted.toExponential(6)} matches the established reference ${reference.netFractionalRate.toExponential(6)} within tolerance (residual ${residual.toExponential(3)} <= ${COMPOSITION_TOLERANCE}).`,
      };
    }
    return {
      verdict: 'FALSIFIED',
      reasoning: `Predicted ${predicted.toExponential(6)} does NOT match the established reference ${reference.netFractionalRate.toExponential(6)} (residual ${residual.toExponential(3)} exceeds tolerance ${COMPOSITION_TOLERANCE}).`,
    };
  });

  return candidate;
}

export interface GeneratedPhysicsModelCandidatesResult {
  contractVersion: string;
  referenceFingerprint: string;
  candidates: readonly GeneratedHypothesis[];
  resultFingerprint: string;
}

function fingerprintOf(referenceFingerprint: string, candidates: readonly GeneratedHypothesis[]): string {
  const json = JSON.stringify({ referenceFingerprint, candidates: candidates.map((c) => c.fingerprint).sort() });
  let hash = 0x811c9dc5;
  for (let i = 0; i < json.length; i++) {
    hash ^= json.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16);
}

/**
 * Generates both composition candidates and tests each against a FRESH real
 * derivation of the GPS case (never a cached or hand-typed reference).
 */
export function generatePhysicsModelCandidates(): GeneratedPhysicsModelCandidatesResult {
  const reference = runRelativisticTimeDilationCase();
  const candidates = COMPOSITION_RULES.map((rule) => buildCandidate(rule, reference));
  return {
    contractVersion: GENERATED_PHYSICS_MODEL_CANDIDATES_VERSION,
    referenceFingerprint: reference.resultFingerprint,
    candidates,
    resultFingerprint: fingerprintOf(reference.resultFingerprint, candidates),
  };
}

export function replayGeneratedPhysicsModelCandidates(saved: GeneratedPhysicsModelCandidatesResult): HypothesisGenerationReplay {
  const recomputed = generatePhysicsModelCandidates();
  if (recomputed.referenceFingerprint !== saved.referenceFingerprint) {
    return { status: 'DRIFT', reason: `The GPS reference case itself drifted (${saved.referenceFingerprint} -> ${recomputed.referenceFingerprint}) — a declared constant or formula changed since this run was saved.` };
  }
  if (recomputed.resultFingerprint !== saved.resultFingerprint) {
    return { status: 'DRIFT', reason: `The reference matched but recomputing the generated candidates produced a different fingerprint (${saved.resultFingerprint} -> ${recomputed.resultFingerprint}).` };
  }
  return { status: 'MATCH', reason: '' };
}

export function saveGeneratedPhysicsModelCandidatesToMemory(result: GeneratedPhysicsModelCandidatesResult): SavedExperiment {
  const supported = result.candidates.filter((c) => c.verdict === 'SUPPORTED').length;
  const falsified = result.candidates.filter((c) => c.verdict === 'FALSIFIED').length;
  return saveExperiment({
    labId: 'physics-generated-model-candidates',
    experimentId: `generated-gps-composition:${result.resultFingerprint}`,
    experimentName: 'Generated GPS composition-rule candidates (known-equation transformation)',
    params: { referenceFingerprint: result.referenceFingerprint, candidateCount: result.candidates.length },
    stats: { supported, falsified },
    analysis: result.candidates.map((c) => ({ title: c.hypothesisId, kind: 'generated-hypothesis', body: `[${c.verdict}] ${c.verdictReasoning ?? ''}` })),
    honesty: 'simplified',
    honestyNote:
      'Both candidates were GENERATED by composing two already-declared real models, not hand-authored. Each is tested against a freshly recomputed real reference value, never a cached or asserted one. '
      + 'SUPPORTED here means "matches the established formula", never a claim of new scientific confirmation.',
    epistemicStatus: `GENERATED=${result.candidates.length};SUPPORTED=${supported};FALSIFIED=${falsified}`,
    assumptions: ['Composition is limited to two enumerable rules (signed difference, quadrature sum); no other functional form is attempted in this pass.'],
  });
}
