import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import { ShaderPass } from 'three/examples/jsm/postprocessing/ShaderPass.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { isSuppressed } from './MatrixDataStream';
import { pushHoloPoint } from '../core/holoTelemetry';

/**
 * GENESIS HOLO BACKDROP — the full-bleed world behind the whole shell.
 *
 * This is the primary viewport of the 2040 shell, not a thumbnail: a fixed
 * 100vw × 100vh WebGL canvas that every piece of UI floats over as a HUD.
 * It renders a NON-EUCLIDEAN PORTAL between two worlds with real
 * post-processing, seeded so it is the same world for everyone:
 *
 *   - world A — a red alien desert: a hairline terrain grid, ring of seeded
 *     monoliths on the horizon, a low copper sun;
 *   - world B — a luminous dimension: emissive spires under a cyan sky whose
 *     sky itself is a GPU raymarched (SDF) megalithic architecture — domes and
 *     colonnades generated by distance fields, rendered to a small texture;
 *   - the portal — a plane whose shader samples a render target (FBO) that
 *     holds the OTHER world rendered from the same camera every frame, warped
 *     by a gravitational-lens distortion with chromatic aberration and a
 *     plasma ring. The camera flies through it; on crossing the event horizon
 *     the two worlds swap, so there is never a cut and never a black frame;
 *   - the frame goes through EffectComposer: RenderPass → UnrealBloomPass →
 *     a chromatic-aberration ShaderPass → OutputPass, with ACES filmic tone
 *     mapping. On phones the composer is skipped and the FBO is half size.
 *
 * Budget discipline (this is atmosphere, the solvers own the CPU):
 *   - device-pixel-ratio capped (1.5 desktop, 1 phone);
 *   - the rAF loop is CANCELLED (not skipped) when the tab is hidden, when
 *     `prefers-reduced-motion` is set, or on a heavy-3D route — `isSuppressed`
 *     from MatrixDataStream is THE list, so this layer never drifts from it;
 *   - lazy-loaded by AppShell (React.lazy + Suspense), so the initial bundle
 *     does not carry three.js for a decoration.
 *
 * Determinism: no Math.random — a seeded mulberry32 places every monolith and
 * spire, so the world is identical on every machine and every reload.
 *
 * Safety: the renderer is created inside try/catch; on failure NOTHING is
 * allocated and the component renders an inert hidden canvas. Everything it
 * allocates is disposed on unmount.
 */

/** Pure decision: should the loop be running right now? */
export function shouldAnimate(state: { hidden: boolean; reducedMotion: boolean; hash: string }): boolean {
  return !state.hidden && !state.reducedMotion && !isSuppressed(state.hash);
}

export interface HoloBackdropOptions {
  /** Upper bound for the device pixel ratio actually used (default 1.5). */
  maxPixelRatio?: number;
  /** Skip the post-processing composer and halve the portal FBO (phones). */
  lowPower?: boolean;
  /** Seed for the deterministic world layout (default GENESIS). */
  seed?: number;
}

/** Deterministic PRNG (mulberry32) — the world layout must not depend on Math.random. */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const PORTAL_VERTEX = /* glsl */ `
varying vec2 vUv;
void main() { vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }
`;

/** Gravitational-lens warp + chromatic aberration + plasma ring; discards outside the disc. */
const PORTAL_FRAGMENT = /* glsl */ `
uniform sampler2D tDiffuse;
uniform float uTime;
uniform vec3 uRing;
varying vec2 vUv;
void main() {
  vec2 center = vec2(0.5);
  vec2 delta = vUv - center;
  float dist = length(delta);
  if (dist > 0.5) discard;
  float distortion = smoothstep(0.5, 0.0, dist) * 0.22;
  vec2 dir = dist > 0.0001 ? delta / dist : vec2(0.0);
  vec2 warped = center + dir * (dist + distortion * sin(dist * 24.0 - uTime * 5.0));
  float r = texture2D(tDiffuse, warped + vec2(0.006 * dist, 0.0)).r;
  float g = texture2D(tDiffuse, warped).g;
  float b = texture2D(tDiffuse, warped - vec2(0.006 * dist, 0.0)).b;
  vec3 color = vec3(r, g, b);
  float ring = smoothstep(0.455, 0.5, dist) - smoothstep(0.5, 0.545, dist);
  color += uRing * ring * 2.4;
  float rim = smoothstep(0.30, 0.5, dist) * 0.35;
  color += uRing * rim * (0.5 + 0.5 * sin(uTime * 2.0 + dist * 40.0));
  gl_FragColor = vec4(color, 1.0);
}
`;

/** SDF-raymarched megalithic architecture (domes, colonnades, resonant floor) — world B's sky. */
const SDF_SKY_FRAGMENT = /* glsl */ `
uniform float uTime;
uniform vec2 uResolution;
uniform float uSteps;
varying vec2 vUv;
mat2 rot(float a) { float c = cos(a), s = sin(a); return mat2(c, -s, s, c); }
float sdf(vec3 p) {
  p.xy *= rot(p.z * 0.05 + uTime * 0.08);
  vec3 q = mod(p, 6.0) - 3.0;
  float columns = length(q.xz) - 0.8;
  vec3 d = p; d.y -= 2.5;
  float dome = length(d) - 2.0;
  float structure = min(columns, dome);
  float floorPlane = p.y + 3.0;
  return min(floorPlane, structure);
}
void main() {
  vec2 st = (vUv - 0.5) * vec2(uResolution.x / uResolution.y, 1.0);
  vec3 ro = vec3(0.0, 1.0, -uTime * 1.6);
  vec3 rd = normalize(vec3(st, 1.0 - dot(st, st) * 0.2));
  rd.xy *= rot(sin(uTime * 0.1) * 0.2);
  float t = 0.0; float hit = 0.0;
  for (int i = 0; i < 96; i++) {
    if (float(i) >= uSteps) break;
    vec3 p = ro + rd * t;
    float d = sdf(p);
    if (d < 0.001) { hit = 1.0; break; }
    t += d;
    if (t > 50.0) break;
  }
  vec3 col = vec3(0.004, 0.02, 0.06);
  if (hit > 0.5) {
    float lighting = 1.0 - t / 50.0;
    col = mix(vec3(0.02, 0.05, 0.09), vec3(0.55, 0.9, 1.0), lighting);
    col += vec3(0.0, 0.35, 0.6) * (1.0 - abs(rd.y)) * 0.5;
  }
  gl_FragColor = vec4(col * 0.55, 1.0);
}
`;

const ABERRATION_SHADER = {
  uniforms: { tDiffuse: { value: null as THREE.Texture | null }, uAmount: { value: 0.0016 } },
  vertexShader: PORTAL_VERTEX,
  fragmentShader: /* glsl */ `
uniform sampler2D tDiffuse;
uniform float uAmount;
varying vec2 vUv;
void main() {
  vec2 d = (vUv - 0.5) * uAmount * length(vUv - 0.5) * 4.0;
  float r = texture2D(tDiffuse, vUv + d).r;
  float g = texture2D(tDiffuse, vUv).g;
  float b = texture2D(tDiffuse, vUv - d).b;
  float a = texture2D(tDiffuse, vUv).a;
  gl_FragColor = vec4(r, g, b, a);
}
`,
};

/**
 * Builds the two worlds, the portal and the post chain against a canvas and
 * starts the loop. Returns the dispose function, or `null` when a WebGL
 * renderer could not be created — in which case NOTHING was allocated.
 *
 * Split out of the React component so it can be exercised without a DOM: a
 * fake canvas with no WebGL context must yield `null`, never a throw.
 */
export function mountHoloBackdrop(
  canvas: HTMLCanvasElement,
  win: Window & typeof globalThis,
  options: HoloBackdropOptions = {},
): (() => void) | null {
  let renderer: THREE.WebGLRenderer;
  try {
    renderer = new THREE.WebGLRenderer({ canvas, antialias: false, powerPreference: 'high-performance' });
  } catch {
    return null;
  }

  const doc = canvas.ownerDocument;
  const random = mulberry32(options.seed ?? 0x47454e45);
  const lowPower = options.lowPower ?? false;
  const dpr = Math.min(options.maxPixelRatio ?? 1.5, win.devicePixelRatio || 1);
  renderer.setPixelRatio(dpr);
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.0;

  const camera = new THREE.PerspectiveCamera(66, 1, 0.05, 400);
  camera.position.set(0, 2.2, 8);
  const disposables: { dispose(): void }[] = [];
  const track = <T extends { dispose(): void }>(d: T): T => { disposables.push(d); return d; };

  // --- world A: red alien desert ------------------------------------------
  const worldA = new THREE.Scene();
  worldA.background = new THREE.Color(0x140604);
  worldA.fog = new THREE.FogExp2(0x1a0805, 0.018);
  const gridA = new THREE.GridHelper(140, 90, 0xff5a1f, 0x3a1206);
  (gridA.material as THREE.Material).transparent = true;
  (gridA.material as THREE.Material).opacity = 0.42;
  track(gridA.geometry); track(gridA.material as THREE.Material);
  worldA.add(gridA);
  worldA.add(new THREE.HemisphereLight(0xff8a50, 0x2a0a04, 0.9));
  const sunA = new THREE.DirectionalLight(0xffb070, 2.6);
  sunA.position.set(-30, 8, -40);
  worldA.add(sunA);
  const monolithGeo = track(new THREE.BoxGeometry(1, 1, 1));
  const monolithMat = track(new THREE.MeshStandardMaterial({ color: 0x2b1008, roughness: 0.85, metalness: 0.3, emissive: 0x3a1206, emissiveIntensity: 0.35 }));
  for (let i = 0; i < 22; i++) {
    const height = 8 + random() * 22;
    const monolith = new THREE.Mesh(monolithGeo, monolithMat);
    const angle = (i / 22) * Math.PI * 2 + random() * 0.2;
    const radius = 34 + random() * 16;
    monolith.scale.set(2 + random() * 1.5, height, 2 + random() * 1.5);
    monolith.position.set(Math.cos(angle) * radius, height / 2, Math.sin(angle) * radius - 10);
    monolith.rotation.y = random() * Math.PI;
    worldA.add(monolith);
  }
  const sunDisc = new THREE.Mesh(track(new THREE.CircleGeometry(6, 48)), track(new THREE.MeshBasicMaterial({ color: 0xc94a18, fog: false })));
  sunDisc.position.set(-70, 14, -120);
  sunDisc.lookAt(camera.position);
  worldA.add(sunDisc);

  // --- world B: luminous dimension under an SDF-raymarched sky ------------
  const worldB = new THREE.Scene();
  worldB.fog = new THREE.FogExp2(0x02101f, 0.014);
  const skyTarget = track(new THREE.WebGLRenderTarget(lowPower ? 256 : 512, lowPower ? 144 : 288, { format: THREE.RGBAFormat }));
  worldB.background = skyTarget.texture;
  const skyScene = new THREE.Scene();
  const skyCamera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
  const skyMaterial = track(new THREE.ShaderMaterial({
    vertexShader: PORTAL_VERTEX,
    fragmentShader: SDF_SKY_FRAGMENT,
    uniforms: { uTime: { value: 0 }, uResolution: { value: new THREE.Vector2(512, 288) }, uSteps: { value: lowPower ? 40 : 80 } },
    depthWrite: false, depthTest: false,
  }));
  skyScene.add(new THREE.Mesh(track(new THREE.PlaneGeometry(2, 2)), skyMaterial));
  worldB.add(new THREE.HemisphereLight(0x8ee8f5, 0x03101c, 0.8));
  const sunB = new THREE.DirectionalLight(0x38bdf8, 4.5);
  sunB.position.set(18, 36, 18);
  worldB.add(sunB);
  const spireGeo = track(new THREE.ConeGeometry(1, 1, 6));
  const spireMat = track(new THREE.MeshStandardMaterial({ color: 0x0f172a, emissive: 0x0ea5e9, emissiveIntensity: 0.75, roughness: 0.12, metalness: 0.92 }));
  for (let i = 0; i < 38; i++) {
    const height = 5 + random() * 15;
    const spire = new THREE.Mesh(spireGeo, spireMat);
    spire.scale.set(0.5 + random() * 1.4, height, 0.5 + random() * 1.4);
    spire.position.set((random() - 0.5) * 64, height / 2, (random() - 0.5) * 64 - 22);
    worldB.add(spire);
  }
  const gridB = new THREE.GridHelper(140, 70, 0x8ee8f5, 0x0b2a3a);
  (gridB.material as THREE.Material).transparent = true;
  (gridB.material as THREE.Material).opacity = 0.22;
  track(gridB.geometry); track(gridB.material as THREE.Material);
  worldB.add(gridB);

  // --- the portal: FBO of the OTHER world, lensed --------------------------
  const fboScale = lowPower ? 0.5 : 1;
  const portalTarget = track(new THREE.WebGLRenderTarget(2, 2, { format: THREE.RGBAFormat }));
  const portalMaterial = track(new THREE.ShaderMaterial({
    vertexShader: PORTAL_VERTEX,
    fragmentShader: PORTAL_FRAGMENT,
    uniforms: { tDiffuse: { value: portalTarget.texture }, uTime: { value: 0 }, uRing: { value: new THREE.Color(1.0, 0.42, 0.12) } },
    side: THREE.DoubleSide,
  }));
  const portal = new THREE.Mesh(track(new THREE.PlaneGeometry(10, 10)), portalMaterial);
  portal.position.set(0, 3.2, -6);
  worldA.add(portal);

  const RING_A = new THREE.Color(1.0, 0.42, 0.12); // copper: seen from the desert
  const RING_B = new THREE.Color(0.1, 0.85, 1.0); // cyan: seen from the luminous world
  let active = worldA;
  let target = worldB;

  // --- post chain ------------------------------------------------------------
  const renderPass = new RenderPass(active, camera);
  let composer: EffectComposer | null = null;
  let bloom: UnrealBloomPass | null = null;
  if (!lowPower) {
    composer = track(new EffectComposer(renderer));
    composer.setPixelRatio(dpr);
    composer.addPass(renderPass);
    bloom = track(new UnrealBloomPass(new THREE.Vector2(1, 1), 0.55, 0.4, 0.86));
    composer.addPass(bloom);
    composer.addPass(track(new ShaderPass(ABERRATION_SHADER)));
    composer.addPass(track(new OutputPass()));
  }

  // --- loop, guarded by shouldAnimate ---------------------------------------
  const motionQuery = win.matchMedia?.('(prefers-reduced-motion: reduce)');
  let raf = 0;
  let last = 0;
  let width = 1;
  let height = 1;
  let parallaxX = 0;
  let parallaxY = 0;
  let pointerX = 0;
  let pointerY = 0;
  const FRAME_MS = lowPower ? 1000 / 30 : 0;
  const START_Z = 8;
  let lastSample = 0;
  const SAMPLE_MS = 250;

  const state = (): { hidden: boolean; reducedMotion: boolean; hash: string } => ({
    hidden: doc.hidden,
    reducedMotion: motionQuery?.matches ?? false,
    hash: win.location.hash,
  });

  const layout = (): void => {
    width = Math.max(1, win.innerWidth);
    height = Math.max(1, win.innerHeight);
    camera.aspect = width / height;
    camera.updateProjectionMatrix();
    renderer.setSize(width, height, false);
    composer?.setSize(width, height);
    bloom?.setSize(width, height);
    portalTarget.setSize(Math.max(2, Math.floor(width * dpr * fboScale)), Math.max(2, Math.floor(height * dpr * fboScale)));
  };

  const frame = (now: number): void => {
    if (!shouldAnimate(state())) { raf = 0; return; }
    raf = win.requestAnimationFrame(frame);
    if (now - last < FRAME_MS) return;
    const dt = last === 0 ? 1 / 60 : Math.min(0.05, (now - last) / 1000);
    last = now;
    const t = now * 0.001;
    portalMaterial.uniforms.uTime.value = t;
    skyMaterial.uniforms.uTime.value = t;

    // Fly toward the gate; cross the event horizon → swap worlds, no cut.
    camera.position.z -= dt * 1.1;
    parallaxX += (pointerX * 0.6 - parallaxX) * 0.04;
    parallaxY += (pointerY * 0.35 - parallaxY) * 0.04;
    camera.position.x = parallaxX;
    camera.position.y = 2.2 + parallaxY;
    camera.lookAt(0, 3.0, camera.position.z - 10);
    if (camera.position.z <= portal.position.z + 0.25) {
      const previous = active;
      active = target;
      target = previous;
      camera.position.z = START_Z;
      renderPass.scene = active;
      active.add(portal);
      portalMaterial.uniforms.uRing.value = active === worldA ? RING_A : RING_B;
    }
    portal.rotation.y = Math.sin(t * 0.3) * 0.08;
    // The camera's real flight path, as 5D samples for the manifold engine:
    // (x, y, z, t seconds, w = signed distance to the portal plane).
    if (now - lastSample >= SAMPLE_MS) {
      lastSample = now;
      pushHoloPoint({ x: camera.position.x, y: camera.position.y, z: camera.position.z, temporalT: t, hyperspaceW: camera.position.z - portal.position.z });
    }

    // 1. world B's sky (SDF architecture) — small texture, every frame.
    renderer.setRenderTarget(skyTarget);
    renderer.render(skyScene, skyCamera);
    // 2. the other world, seen from this camera, into the portal FBO.
    portal.visible = false;
    renderer.setRenderTarget(portalTarget);
    renderer.render(target, camera);
    portal.visible = true;
    renderer.setRenderTarget(null);
    // 3. this world + the portal, through the post chain.
    if (composer) composer.render(); else renderer.render(active, camera);
  };

  const kick = (): void => {
    const allowed = shouldAnimate(state());
    canvas.style.opacity = isSuppressed(win.location.hash) ? '0' : '';
    if (allowed && raf === 0) { last = 0; raf = win.requestAnimationFrame(frame); }
  };

  const onVisibility = (): void => kick();
  const onHashChange = (): void => kick();
  const onMotionChange = (): void => kick();
  const onResize = (): void => { layout(); kick(); };
  const onPointer = (e: PointerEvent): void => {
    pointerX = (e.clientX / width - 0.5) * 2;
    pointerY = -(e.clientY / height - 0.5) * 2;
  };

  layout();
  kick();
  win.addEventListener('resize', onResize);
  win.addEventListener('hashchange', onHashChange);
  win.addEventListener('pointermove', onPointer, { passive: true });
  doc.addEventListener('visibilitychange', onVisibility);
  motionQuery?.addEventListener?.('change', onMotionChange);

  return () => {
    if (raf !== 0) win.cancelAnimationFrame(raf);
    raf = 0;
    win.removeEventListener('resize', onResize);
    win.removeEventListener('hashchange', onHashChange);
    win.removeEventListener('pointermove', onPointer);
    doc.removeEventListener('visibilitychange', onVisibility);
    motionQuery?.removeEventListener?.('change', onMotionChange);
    for (const d of disposables) d.dispose();
    worldA.clear(); worldB.clear(); skyScene.clear();
    renderer.setRenderTarget(null);
    renderer.dispose();
    renderer.forceContextLoss();
  };
}

export function GenesisHoloBackdrop(): JSX.Element | null {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    if (typeof window === 'undefined' || typeof document === 'undefined') return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const phone = window.innerWidth < 720;
    const dispose = mountHoloBackdrop(canvas, window, { maxPixelRatio: phone ? 1 : 1.5, lowPower: phone });
    if (dispose === null) {
      // No WebGL here (jsdom, a blocked GPU, a very old device): render nothing.
      canvas.hidden = true;
      return;
    }
    return dispose;
  }, []);

  return <canvas ref={canvasRef} className="holo-backdrop" aria-hidden="true" data-testid="holo-backdrop" />;
}

export default GenesisHoloBackdrop;
