"""Biopython PDB structural-comparison worker for Genesis Fabric.

Performs only manifest-approved comparisons of publicly deposited HIV MPER / 10E8
structures. It does not dock, generate a mutation, estimate affinity, or make a
clinical or vaccine-efficacy prediction.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

# Each profile is an experimentally deposited comparison protocol. 5T29 is an
# experimentally deposited 10E8 light-chain-mutant/scaffold complex, not a
# variant generated by Genesis.
PAIR_PROFILES = {
    ("5GHW", "4G6F"): {
        "label": "10E8 long epitope versus public gp41 MPER peptide",
        "fab": (("H", "H"), ("L", "L")),
        "mper": ("P", "P"),
        "mperMode": "residue_id_identical",
    },
    ("5GHW", "5WDF"): {
        "label": "10E8 reference versus deposited 10E8v4-5R+100cF gp41-peptide complex",
        "fab": (("H", "H"), ("L", "L")),
        "mper": ("P", "P"),
        "mperMode": "residue_id_identical",
    },
}
BASE_REQUIRED_PDBS = {"5GHW", "4G6F"}
RCSB_PDB_RECORD_URL = "https://www.rcsb.org/structure/{pdb_id}"
RCSB_PDB_DOWNLOAD_URL = "https://files.rcsb.org/download/{pdb_id}.pdb"
RCSB_PDB_USAGE_POLICY_URL = "https://www.rcsb.org/pages/usage-policy"
PDB_ARCHIVE_LICENSE = "CC0-1.0"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_structure(parser, root: Path, pdb_id: str):
    path = root / f"{pdb_id}.pdb"
    if not path.is_file():
        raise ValueError(f"missing_pdb_artifact:{pdb_id}")
    return parser.get_structure(pdb_id, path)[0], path


def pdb_artifact_provenance(pdb_id: str, path: Path):
    """Return source-bound metadata for the exact local PDB bytes used by the run.

    The source URL identifies the public archive record; the SHA-256 identifies
    the exact locally verified copy. No retrieval timestamp is invented.
    """
    return {
        "artifactType": "PDB_COORDINATE_FILE",
        "pdbId": pdb_id,
        "recordUrl": RCSB_PDB_RECORD_URL.format(pdb_id=pdb_id),
        "downloadUrl": RCSB_PDB_DOWNLOAD_URL.format(pdb_id=pdb_id),
        "sha256": sha256(path),
        "license": PDB_ARCHIVE_LICENSE,
        "licenseUrl": RCSB_PDB_USAGE_POLICY_URL,
        "attribution": "RCSB Protein Data Bank / wwPDB; original depositors should be attributed where possible.",
    }


def standard_residues(chain):
    return [residue for residue in chain.get_residues() if residue.id[0] == " " and "CA" in residue]


def atom_pairs_by_residue_id(reference_chain, mobile_chain):
    reference = {residue.id[1]: residue for residue in standard_residues(reference_chain)}
    mobile = {residue.id[1]: residue for residue in standard_residues(mobile_chain)}
    pairs = []
    for residue_id in sorted(set(reference) & set(mobile)):
        ref_residue, mob_residue = reference[residue_id], mobile[residue_id]
        if ref_residue.resname == mob_residue.resname:
            pairs.append((ref_residue["CA"], mob_residue["CA"], residue_id))
    return pairs


def atom_pairs_longest_identical_segment(reference_chain, mobile_chain):
    """Return Cα pairs for the longest contiguous residue-identical segment.

    This deliberately avoids inferring a full structural alignment for a
    scaffold context. It reports only an observed contiguous identical segment.
    """
    reference, mobile = standard_residues(reference_chain), standard_residues(mobile_chain)
    best = (0, 0, 0)
    for ref_index in range(len(reference)):
        for mob_index in range(len(mobile)):
            size = 0
            while (ref_index + size < len(reference) and mob_index + size < len(mobile)
                   and reference[ref_index + size].resname == mobile[mob_index + size].resname):
                size += 1
            if size > best[2]:
                best = (ref_index, mob_index, size)
    ref_index, mob_index, size = best
    return [
        (reference[ref_index + offset]["CA"], mobile[mob_index + offset]["CA"], reference[ref_index + offset].id[1])
        for offset in range(size)
    ]


def detect():
    try:
        import Bio  # noqa: F401
        from Bio.PDB import PDBParser  # noqa: F401
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "error": f"biopython_unavailable:{exc}"}
    root_value = os.environ.get("GENESIS_PDB_STRUCTURES_DIR", "")
    if not root_value:
        return {"ok": False, "error": "missing_GENESIS_PDB_STRUCTURES_DIR"}
    root = Path(root_value)
    missing = [pdb_id for pdb_id in sorted(BASE_REQUIRED_PDBS) if not (root / f"{pdb_id}.pdb").is_file()]
    if missing:
        return {"ok": False, "error": f"missing_pdb_artifact:{','.join(missing)}"}
    import Bio
    available = {pdb_id: sha256(root / f"{pdb_id}.pdb") for pdb_id in {"5GHW", "4G6F", "5WDF"} if (root / f"{pdb_id}.pdb").is_file()}
    return {"ok": True, "version": Bio.__version__, "artifacts": available}


def compare(req):
    from Bio import __version__ as biopython_version
    from Bio.PDB import PDBParser, Superimposer

    reference_id, mobile_id = req.get("referencePdb", ""), req.get("mobilePdb", "")
    profile = PAIR_PROFILES.get((reference_id, mobile_id))
    if not profile:
        return {"ok": False, "error": "unsupported_pdb_pair"}

    root = Path(os.environ["GENESIS_PDB_STRUCTURES_DIR"])
    parser = PDBParser(QUIET=True)
    reference, reference_path = load_structure(parser, root, reference_id)
    mobile, mobile_path = load_structure(parser, root, mobile_id)

    fab_pairs = []
    for reference_chain, mobile_chain in profile["fab"]:
        fab_pairs.extend(atom_pairs_by_residue_id(reference[reference_chain], mobile[mobile_chain]))
    if len(fab_pairs) < 3:
        return {"ok": False, "error": "insufficient_fab_ca_pairs"}
    superimposer = Superimposer()
    superimposer.set_atoms([pair[0] for pair in fab_pairs], [pair[1] for pair in fab_pairs])
    fab_rmsd = float(superimposer.rms)

    reference_mper, mobile_mper = profile["mper"]
    mper_pairs = (atom_pairs_by_residue_id(reference[reference_mper], mobile[mobile_mper])
                  if profile["mperMode"] == "residue_id_identical"
                  else atom_pairs_longest_identical_segment(reference[reference_mper], mobile[mobile_mper]))
    if len(mper_pairs) < 3:
        return {"ok": False, "error": "insufficient_mper_ca_pairs"}
    transformed_mobile = [pair[1].copy() for pair in mper_pairs]
    superimposer.apply(transformed_mobile)
    mper_rmsd = float((sum(float(((pair[0].coord - transformed.coord) ** 2).sum())
                            for pair, transformed in zip(mper_pairs, transformed_mobile)) / len(mper_pairs)) ** 0.5)

    return {
        "ok": True,
        "data": {
            "fab10e8RmsdAngstrom": fab_rmsd,
            "fabMatchedCaAtoms": len(fab_pairs),
            "mperInFabAlignedFrameRmsdAngstrom": mper_rmsd,
            "mperMatchedIdenticalCaAtoms": len(mper_pairs),
        },
        "engine": f"Biopython {biopython_version}",
        "provenance": {
            "method": "PDBParser + C-alpha least-squares Fab superposition",
            "pairProfile": profile["label"],
            "referencePdb": reference_id, "mobilePdb": mobile_id,
            "referenceSha256": sha256(reference_path), "mobileSha256": sha256(mobile_path),
            "inputArtifacts": [
                pdb_artifact_provenance(reference_id, reference_path),
                pdb_artifact_provenance(mobile_id, mobile_path),
            ],
            "sourceArchive": "RCSB Protein Data Bank / wwPDB",
            "sourceLicense": PDB_ARCHIVE_LICENSE,
            "sourceLicenseUrl": RCSB_PDB_USAGE_POLICY_URL,
            "fabChainMapping": [{"reference": ref, "mobile": mob} for ref, mob in profile["fab"]],
            "mperChainMapping": {"reference": reference_mper, "mobile": mobile_mper},
            "mperPairingMode": profile["mperMode"],
            "requiredEnvironmentVariables": ["GENESIS_BIOPYTHON_PYTHON", "GENESIS_PDB_STRUCTURES_DIR"],
            "classification": "COMPUTATIONAL_RESULT",
        },
    }


def main():
    try:
        req = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
    except Exception as exc:  # noqa: BLE001
        print(json.dumps({"ok": False, "error": f"bad_request:{exc}"})); return
    if req.get("cmd") == "detect":
        print(json.dumps(detect())); return
    if req.get("cmd") == "compare10e8Mper":
        status = detect()
        if not status.get("ok"):
            print(json.dumps(status)); return
        try:
            print(json.dumps(compare(req)))
        except Exception as exc:  # noqa: BLE001
            print(json.dumps({"ok": False, "error": f"comparison_failed:{exc}"}))
        return
    print(json.dumps({"ok": False, "error": "unknown_command"}))


if __name__ == "__main__":
    main()
